# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lb_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 450)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(145, 20, 160, 40))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl1 = QtWidgets.QLabel(Form)
        self.lbl1.setGeometry(QtCore.QRect(120, 60, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl1.setFont(font)
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(Form)
        self.lbl2.setGeometry(QtCore.QRect(120, 100, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl2.setFont(font)
        self.lbl2.setText("")
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(Form)
        self.lbl3.setGeometry(QtCore.QRect(120, 140, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl3.setFont(font)
        self.lbl3.setText("")
        self.lbl3.setObjectName("lbl3")
        self.lbl4 = QtWidgets.QLabel(Form)
        self.lbl4.setGeometry(QtCore.QRect(120, 180, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl4.setFont(font)
        self.lbl4.setText("")
        self.lbl4.setObjectName("lbl4")
        self.lbl8 = QtWidgets.QLabel(Form)
        self.lbl8.setGeometry(QtCore.QRect(120, 340, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl8.setFont(font)
        self.lbl8.setText("")
        self.lbl8.setObjectName("lbl8")
        self.lbl6 = QtWidgets.QLabel(Form)
        self.lbl6.setGeometry(QtCore.QRect(120, 260, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl6.setFont(font)
        self.lbl6.setText("")
        self.lbl6.setObjectName("lbl6")
        self.lbl7 = QtWidgets.QLabel(Form)
        self.lbl7.setGeometry(QtCore.QRect(120, 300, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl7.setFont(font)
        self.lbl7.setText("")
        self.lbl7.setObjectName("lbl7")
        self.lbl5 = QtWidgets.QLabel(Form)
        self.lbl5.setGeometry(QtCore.QRect(120, 220, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl5.setFont(font)
        self.lbl5.setText("")
        self.lbl5.setObjectName("lbl5")
        self.lbl9 = QtWidgets.QLabel(Form)
        self.lbl9.setGeometry(QtCore.QRect(120, 380, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl9.setFont(font)
        self.lbl9.setText("")
        self.lbl9.setObjectName("lbl9")
        self.lbl10 = QtWidgets.QLabel(Form)
        self.lbl10.setGeometry(QtCore.QRect(120, 420, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl10.setFont(font)
        self.lbl10.setText("")
        self.lbl10.setObjectName("lbl10")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Доска почёта"))
        self.label.setText(_translate("Form", "Доска почёта"))
