# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_conditions = QtWidgets.QLabel(self.centralwidget)
        self.label_conditions.setEnabled(False)
        self.label_conditions.setGeometry(QtCore.QRect(20, 40, 430, 520))
        self.label_conditions.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_conditions.setFrameShape(QtWidgets.QFrame.Box)
        self.label_conditions.setObjectName("label_conditions")
        self.label_solution = QtWidgets.QLabel(self.centralwidget)
        self.label_solution.setEnabled(False)
        self.label_solution.setGeometry(QtCore.QRect(470, 40, 430, 520))
        self.label_solution.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_solution.setFrameShape(QtWidgets.QFrame.Box)
        self.label_solution.setObjectName("label_solution")
        self.label_text1 = QtWidgets.QLabel(self.centralwidget)
        self.label_text1.setEnabled(False)
        self.label_text1.setGeometry(QtCore.QRect(20, 4, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_text1.setFont(font)
        self.label_text1.setObjectName("label_text1")
        self.label_text2 = QtWidgets.QLabel(self.centralwidget)
        self.label_text2.setEnabled(False)
        self.label_text2.setGeometry(QtCore.QRect(470, 4, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_text2.setFont(font)
        self.label_text2.setObjectName("label_text2")
        self.btn_leaderboard = QtWidgets.QPushButton(self.centralwidget)
        self.btn_leaderboard.setEnabled(False)
        self.btn_leaderboard.setGeometry(QtCore.QRect(1000, 10, 180, 50))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.btn_leaderboard.setFont(font)
        self.btn_leaderboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_leaderboard.setObjectName("btn_leaderboard")
        self.input_answer = QtWidgets.QLineEdit(self.centralwidget)
        self.input_answer.setEnabled(False)
        self.input_answer.setGeometry(QtCore.QRect(1000, 470, 180, 50))
        self.input_answer.setInputMask("")
        self.input_answer.setText("")
        self.input_answer.setObjectName("input_answer")
        self.btn_solve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_solve.setEnabled(False)
        self.btn_solve.setGeometry(QtCore.QRect(1000, 530, 180, 50))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.btn_solve.setFont(font)
        self.btn_solve.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_solve.setObjectName("btn_solve")
        self.label_text3 = QtWidgets.QLabel(self.centralwidget)
        self.label_text3.setEnabled(False)
        self.label_text3.setGeometry(QtCore.QRect(1000, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text3.setFont(font)
        self.label_text3.setObjectName("label_text3")
        self.label_authors = QtWidgets.QLabel(self.centralwidget)
        self.label_authors.setGeometry(QtCore.QRect(10, 730, 201, 20))
        self.label_authors.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_authors.setObjectName("label_authors")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(900, 640, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setObjectName("btn_start")
        self.label_intro = QtWidgets.QLabel(self.centralwidget)
        self.label_intro.setEnabled(True)
        self.label_intro.setGeometry(QtCore.QRect(20, 20, 1160, 481))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_intro.setFont(font)
        self.label_intro.setFrameShape(QtWidgets.QFrame.Box)
        self.label_intro.setObjectName("label_intro")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(790, 570, 381, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.input_name.setFont(font)
        self.input_name.setInputMask("")
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.label_text4 = QtWidgets.QLabel(self.centralwidget)
        self.label_text4.setGeometry(QtCore.QRect(840, 510, 281, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.label_text4.setFont(font)
        self.label_text4.setObjectName("label_text4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_conditions.setText(_translate("MainWindow", "condition"))
        self.label_solution.setText(_translate("MainWindow", "solution"))
        self.label_text1.setText(_translate("MainWindow", "Условия задачи:"))
        self.label_text2.setText(_translate("MainWindow", "Решение Димы:"))
        self.btn_leaderboard.setText(_translate("MainWindow", "Доска почёта"))
        self.btn_solve.setText(_translate("MainWindow", "Проверить тест!"))
        self.label_text3.setText(_translate("MainWindow", "Ваш тест:"))
        self.label_authors.setText(_translate("MainWindow", "made by @a7ult and @rivaldovsky"))
        self.btn_start.setText(_translate("MainWindow", "Начать игру!"))
        self.label_intro.setText(_translate("MainWindow", "Игра представляет собой \"взлом\" решений для задач, связанных с программированием.\n"
"Вам даются условия задачи, и код Димы, в котором есть недоработка - он решает данную задачу,\n"
"но не полностью - некоторые \"тесты\" он решает верно, а некоторые - нет. Такое иногда случается\n"
"в олимпиадном программировании, и Дима хочет исправить свои ошибки. Помогите Диме найти\n"
"для его решения такой тест, который при введении его в программу, будет возвращать неверный\n"
"результат. Для поиска такого теста вам нужно прочитать код Димы, найти в нём некоторые\n"
"недоработки, и понять, какое число нужно подать в программу, чтобы ответ программы Димы и\n"
"реальный - правильный ответ не совпали."))
        self.label_text4.setText(_translate("MainWindow", "Введите свой никнейм"))
