# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_conditions = QtWidgets.QLabel(self.centralwidget)
        self.label_conditions.setEnabled(False)
        self.label_conditions.setGeometry(QtCore.QRect(20, 40, 430, 520))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_conditions.setFont(font)
        self.label_conditions.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_conditions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_conditions.setObjectName("label_conditions")
        self.label_solution = QtWidgets.QLabel(self.centralwidget)
        self.label_solution.setEnabled(False)
        self.label_solution.setGeometry(QtCore.QRect(470, 40, 430, 520))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_solution.setFont(font)
        self.label_solution.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_solution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_solution.setObjectName("label_solution")
        self.label_text1 = QtWidgets.QLabel(self.centralwidget)
        self.label_text1.setEnabled(False)
        self.label_text1.setGeometry(QtCore.QRect(20, 4, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_text1.setFont(font)
        self.label_text1.setObjectName("label_text1")
        self.label_text2 = QtWidgets.QLabel(self.centralwidget)
        self.label_text2.setEnabled(False)
        self.label_text2.setGeometry(QtCore.QRect(470, 4, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_text2.setFont(font)
        self.label_text2.setObjectName("label_text2")
        self.input_answer = QtWidgets.QLineEdit(self.centralwidget)
        self.input_answer.setEnabled(False)
        self.input_answer.setGeometry(QtCore.QRect(1046, 470, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_answer.setFont(font)
        self.input_answer.setInputMask("")
        self.input_answer.setText("")
        self.input_answer.setObjectName("input_answer")
        self.btn_solve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_solve.setEnabled(False)
        self.btn_solve.setGeometry(QtCore.QRect(1043, 530, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.btn_solve.setFont(font)
        self.btn_solve.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_solve.setObjectName("btn_solve")
        self.label_text3 = QtWidgets.QLabel(self.centralwidget)
        self.label_text3.setEnabled(False)
        self.label_text3.setGeometry(QtCore.QRect(1080, 430, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text3.setFont(font)
        self.label_text3.setObjectName("label_text3")
        self.label_authors = QtWidgets.QLabel(self.centralwidget)
        self.label_authors.setGeometry(QtCore.QRect(10, 730, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_authors.setFont(font)
        self.label_authors.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_authors.setObjectName("label_authors")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(900, 640, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setObjectName("btn_start")
        self.label_intro = QtWidgets.QLabel(self.centralwidget)
        self.label_intro.setEnabled(True)
        self.label_intro.setGeometry(QtCore.QRect(20, 20, 871, 481))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_intro.setFont(font)
        self.label_intro.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_intro.setObjectName("label_intro")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(790, 570, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.input_name.setFont(font)
        self.input_name.setInputMask("")
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.label_text4 = QtWidgets.QLabel(self.centralwidget)
        self.label_text4.setGeometry(QtCore.QRect(840, 510, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label_text4.setFont(font)
        self.label_text4.setObjectName("label_text4")
        self.lbl5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl5.setGeometry(QtCore.QRect(960, 190, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl5.setFont(font)
        self.lbl5.setText("")
        self.lbl5.setObjectName("lbl5")
        self.lbl7 = QtWidgets.QLabel(self.centralwidget)
        self.lbl7.setGeometry(QtCore.QRect(960, 270, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl7.setFont(font)
        self.lbl7.setText("")
        self.lbl7.setObjectName("lbl7")
        self.lbl9 = QtWidgets.QLabel(self.centralwidget)
        self.lbl9.setGeometry(QtCore.QRect(960, 350, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl9.setFont(font)
        self.lbl9.setText("")
        self.lbl9.setObjectName("lbl9")
        self.lbl10 = QtWidgets.QLabel(self.centralwidget)
        self.lbl10.setGeometry(QtCore.QRect(960, 390, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl10.setFont(font)
        self.lbl10.setText("")
        self.lbl10.setObjectName("lbl10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(985, -10, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(960, 30, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl1.setFont(font)
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setGeometry(QtCore.QRect(960, 70, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl2.setFont(font)
        self.lbl2.setText("")
        self.lbl2.setObjectName("lbl2")
        self.lbl4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl4.setGeometry(QtCore.QRect(960, 150, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl4.setFont(font)
        self.lbl4.setText("")
        self.lbl4.setObjectName("lbl4")
        self.lbl8 = QtWidgets.QLabel(self.centralwidget)
        self.lbl8.setGeometry(QtCore.QRect(960, 310, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl8.setFont(font)
        self.lbl8.setText("")
        self.lbl8.setObjectName("lbl8")
        self.lbl6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl6.setGeometry(QtCore.QRect(960, 230, 250, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl6.setFont(font)
        self.lbl6.setText("")
        self.lbl6.setObjectName("lbl6")
        self.lbl3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl3.setGeometry(QtCore.QRect(960, 110, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl3.setFont(font)
        self.lbl3.setText("")
        self.lbl3.setObjectName("lbl3")
        self.label_end = QtWidgets.QLabel(self.centralwidget)
        self.label_end.setEnabled(False)
        self.label_end.setGeometry(QtCore.QRect(20, 60, 851, 321))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_end.setFont(font)
        self.label_end.setObjectName("label_end")
        self.btn_newgame = QtWidgets.QPushButton(self.centralwidget)
        self.btn_newgame.setEnabled(False)
        self.btn_newgame.setGeometry(QtCore.QRect(700, 550, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.btn_newgame.setFont(font)
        self.btn_newgame.setObjectName("btn_newgame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помогите Владику"))
        self.label_conditions.setText(_translate("MainWindow", "condition"))
        self.label_solution.setText(_translate("MainWindow", "solution"))
        self.label_text1.setText(_translate("MainWindow", "Условия задачи:"))
        self.label_text2.setText(_translate("MainWindow", "Решение Димы:"))
        self.btn_solve.setText(_translate("MainWindow", "Проверить тест!"))
        self.label_text3.setText(_translate("MainWindow", "Ваш тест:"))
        self.label_authors.setText(_translate("MainWindow", "made by @a7ult and @rivaldovsky"))
        self.btn_start.setText(_translate("MainWindow", "Начать игру!"))
        self.label_intro.setText(_translate("MainWindow", "Игра представляет собой \"взлом\" решений для задач,\n"
"связанных с программированием. Вам даются условия задачи,\n"
"и код Владика, в нём есть недоработка - он решает\n"
"данную задачу, но не полностью - некоторые \"тесты\" он\n"
"решает верно, а некоторые - нет. Такое иногда случается в\n"
"олимпиадном программировании, и Владик хочет исправить\n"
"свои ошибки. Помогите Владику найти для его решения такой\n"
"тест, который при введении его в программу, будет давать\n"
"неверный результат. Для поиска такого теста вам нужно\n"
"прочитать код Владика, найти в нём некоторые недоработки,\n"
"и понять, какое число нужно подать в программу, чтобы\n"
"ответ программы Владика и реальный (правильный) ответ\n"
"не совпали.\nВажно: в случае, если необходимо ввести несколько\n"
"чисел, вводите их через пробел. Удачи!"))
        self.label_text4.setText(_translate("MainWindow", "Введите свой никнейм"))
        self.label.setText(_translate("MainWindow", "Доска почёта"))
        self.label_end.setText(_translate("MainWindow", "Игра окончена. Ваш результат: 0. Вы прошли 0 уровней"))
        self.btn_newgame.setText(_translate("MainWindow", "Новая игра"))
        self.label_end.setWordWrap(True)
        self.label_conditions.setWordWrap(True)